language: c

script: bash -ex .travis-ci.sh

env:
  - OCAML_VERSION=4.01.0 OPAM_VERSION=1.0.0
  - OCAML_VERSION=4.01.0 OPAM_VERSION=1.1.0
  - OCAML_VERSION=4.00.1 OPAM_VERSION=1.0.0
  - OCAML_VERSION=4.00.1 OPAM_VERSION=1.1.0

after_script: chmod +x ./ocveralls.sh && cd _build && ../ocveralls.sh coverage*.out

